#!/usr/bin/env bash
set -e

dry_run="0"
[[ $1 == "--dry" ]] && dry_run="1"

: "${XDG_CONFIG_HOME:=$HOME/.config}"
: "${DEV_ENV:?env var DEV_ENV needs to be present}"

log() { [[ $dry_run == "1" ]] && echo "[DRY_RUN]: $1" || echo "$1"; }

update_dir() {
    src="$1"; dest="$2"
    log "sync $src -> $dest"
    pushd "$src" >/dev/null
    for c in $(find . -mindepth 1 -maxdepth 1 -type d); do
        target="${dest%/}/${c#./}"
        log "  rm -rf $target"
        [[ $dry_run == "0" ]] && rm -rf "$target"
        log "  cp -r $c $dest"
        [[ $dry_run == "0" ]] && cp -r "$c" "$dest"
    done
    popd >/dev/null
}

copy() {
    src="$1"; dest="$2"
    log "cp $src -> $dest"
    [[ $dry_run == "0" ]] && cp "$src" "$dest"
}

append() {
    src="$1"; dest="$2"
    log "append $src -> $dest"
    [[ $dry_run == "0" ]] && cat "$src" >> "$dest"
}

update_dir "$DEV_ENV/env/.config" "$XDG_CONFIG_HOME"
update_dir "$DEV_ENV/env/.local" "$HOME/.local"

mkdir -p "$HOME/.local/bin" "$HOME/.local/scripts"

copy "$DEV_ENV/env/.tmux.conf" "$HOME/.tmux.conf"
copy "$DEV_ENV/env/.bash_profile" "$HOME/.bash_profile"

if [[ -f "$DEV_ENV/env/.bashrc.append" ]]; then
    touch "$HOME/.bashrc"
    append "$DEV_ENV/env/.bashrc.append" "$HOME/.bashrc"
fi
