#!/usr/bin/env bash
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

if [ -z "$DEV_ENV" ]; then
    echo "env var DEV_ENV needs to be present"; exit 1
fi

grep=""
dry_run="0"
while [[ $# -gt 0 ]]; do
    if [[ "$1" == "--dry" ]]; then dry_run="1"; else grep="$1"; fi
    shift
done

log() { [[ $dry_run == "1" ]] && echo "[DRY_RUN]: $1" || echo "$1"; }

runs_dir=$(find "$script_dir/runs" -mindepth 1 -maxdepth 1 -executable)
for s in $runs_dir; do
    if basename "$s" | grep -vq "$grep"; then log "grep \"$grep\" filtered $s"; continue; fi
    log "running: $s"
    [[ $dry_run == "0" ]] && "$s"
done
